### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Tenyitamas** [BME-MIT-IET/iet-hf-2024-old-imsc3#5]
Az elvégzett munka rövid dokumentációját a saját GitHub tárhely doc könyvtárába rakott fájlba kell írni. A fájlokhoz a [Markdown](https://guides.github.com/features/mastering-markdown/) vagy [AsciiDoc](http://asciidoc.org/) formátumot használjuk. Minden egyes kiválasztott feladatról legyen egy-egy külön fájl: egy-két bekezdés az elvégzett munkáról, képernyőkép (ha releváns), eredmények és tanulságok összefoglalása.

**Comment by ernyei13** [comment]
done
